/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VDialog;

import DAO.MatHangDAO;
import DAO.NhaCungCapDAO;

import Model.NhaCungCap;
import Utils.Formats;
import Utils.PatternRegexs;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JRootPane;
import javax.swing.SwingUtilities;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/**
 *
 * @author quang
 */
public class NhaCungCapDialog extends javax.swing.JDialog {

    /**
     * Creates new form NhaCungCapDialog
     */
    
    
    private NhaCungCap nhaCungCap;
    private boolean isChinhSua;
    private NhaCungCapDAO nhaCungCapDAO;


    
    private void prepareDialog() {
    
     if (this.isChinhSua) {
             this.txtMaNCC.setEditable(false);
             this.txtMaNCC.setText(this.nhaCungCap.getMaNCC());
         }else{
             this.txtMaNCC.setText(getMaNCCMoi());
             this.txtMaNCC.setEditable(false);
        }
        
         
         if (this.isChinhSua) {this.txtTenNCC.setText(this.nhaCungCap.getTenNCC());}
         
         if (this.isChinhSua){ this.txtDiaChi.setText(this.nhaCungCap.getDiaChi());}
         if (this.isChinhSua) {this.txtSDT.setText(this.nhaCungCap.getSoDienThoai());}
         
         
        this.btnThem.addActionListener(btnLuu_Click());
        
    
    }
    
    private ActionListener btnLuu_Click() {
        return new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                
                

                // lấy thông tin khách hàng
                nhaCungCap = new NhaCungCap(
                        txtMaNCC.getText().trim(),
                        txtTenNCC.getText().trim(),
                        txtDiaChi.getText().trim(),
                        txtSDT.getText().trim()   
                );

                // đóng dialog
                dispose();
            }
        };
    }
    
    
    
    
    
    private String getMaNCCMoi() {
        String lastID = "";
        String newID = "";

        // lấy mã khách hàng cuối trong DB
        try {
            lastID = nhaCungCapDAO.getMaNhaCungCapCuoi();
        } catch (Exception e) {
        }

        // Nếu chưa có khách hàng trong DB thì trả về mã mặc định
        if (lastID.isEmpty()) {
            return "NC00001";
        }

        // generate mã khách hàng mới
        Pattern pattern = Pattern.compile(PatternRegexs.REGEX_MANHACUNGCAP);
        Matcher matcher = pattern.matcher(lastID);
        if (matcher.find()) {
            int number = Integer.parseInt(matcher.group(1));
            number++;

            newID = String.format(" NC%05d", number);
        }

        return newID;
    }
    
    public NhaCungCap getNhaCungCap() {
        return nhaCungCap;
    }
    
   
    public NhaCungCapDialog(JFrame frame, NhaCungCap nhaCungCap) throws Exception {
        super(frame, true);
        initComponents();
        
        this.nhaCungCap = nhaCungCap;
        // lấy instance kết nối với db (table MATHANG)
        try {
            nhaCungCapDAO = NhaCungCapDAO.getInstance();
        } catch (Exception e) {
            throw new Exception(e.getMessage());
        }

       
        
        if (nhaCungCap == null) {
            
            isChinhSua = false;
        } else {
           
            isChinhSua = true;
        }

        // tạo GUI
        prepareDialog();

        // đặt button mặc định khi bấm Enter
        JRootPane rootPane = SwingUtilities.getRootPane(this);
        rootPane.setDefaultButton(btnThem);

        // cấu hình cho dialog
        setResizable(false);
       
        setAlwaysOnTop(true);
        setLocationRelativeTo(null);
        
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        txtMaNCC = new javax.swing.JTextField();
        txtTenNCC = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Mã NCC");

        jLabel2.setText("Tên NCC");

        jLabel3.setText("Địa Chỉ");

        jLabel4.setText("Số Điện Thoại");

        btnThem.setText("Lưu");

        btnThoat.setText("Thoát");
        btnThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThoatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaNCC)
                            .addComponent(txtTenNCC)
                            .addComponent(txtDiaChi)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThoat)
                    .addComponent(btnThem))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThoatMouseClicked
        nhaCungCap = null;
        NhaCungCapDialog.this.dispose();
    }//GEN-LAST:event_btnThoatMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtMaNCC;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenNCC;
    // End of variables declaration//GEN-END:variables
}
